# Site settings
title: JTechLog
lead: Viczián István Java blogja
description: Viczián István Java blogja
url: "http://www.jtechlog.hu"
author: Viczián István
twitter_username: vicziani
github_username: vicziani

# Build settings
markdown: kramdown
