# Site settings
title: JTechLog
lead: Viczián István blogja
description: Viczián István blogja
url: "http://www.jtechlog.hu"
author: Viczián István
twitter_username: vicziani
github_username: vicziani

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"